"use strict";
let numero1 = 10;
let numero2 = "20";
console.log(somma(numero1, parseInt(numero2)));
function somma(a, b) {
    return a + b;
}
console.log(prodotto(parseInt("10"), 20));
function prodotto(a, b) {
    return a * b;
}
let corsisti = ["Simone", "Silvio", "Luca", "Matteo"];
console.log(corsisti);
let corsistiAny = ["Simone", 10, true, "Matteo", 11.5];
console.log(corsistiAny);
let city = ["Lecce", "100 a.c.", 100000, true, "Salento", "Puglia"];
city[5] = "Lupiae";
console.log(city);
var MarcheAuto;
(function (MarcheAuto) {
    MarcheAuto[MarcheAuto["FIAT"] = 0] = "FIAT";
    MarcheAuto[MarcheAuto["FORD"] = 1] = "FORD";
    MarcheAuto[MarcheAuto["BMW"] = 2] = "BMW";
    MarcheAuto[MarcheAuto["AUDI"] = 3] = "AUDI";
    MarcheAuto[MarcheAuto["MERCEDES"] = 4] = "MERCEDES";
    MarcheAuto[MarcheAuto["TOYOTA"] = 5] = "TOYOTA";
    MarcheAuto[MarcheAuto["OPEL"] = 6] = "OPEL";
    MarcheAuto[MarcheAuto["PEUGEOT"] = 7] = "PEUGEOT";
    MarcheAuto[MarcheAuto["CITROEN"] = 8] = "CITROEN";
    MarcheAuto[MarcheAuto["RENAULT"] = 9] = "RENAULT";
    MarcheAuto[MarcheAuto["VOLKSWAGEN"] = 10] = "VOLKSWAGEN";
    MarcheAuto[MarcheAuto["ALFA_ROMEO"] = 11] = "ALFA_ROMEO";
    MarcheAuto[MarcheAuto["LANCIA"] = 12] = "LANCIA";
    MarcheAuto[MarcheAuto["JEEP"] = 13] = "JEEP";
    MarcheAuto[MarcheAuto["LAND_ROVER"] = 14] = "LAND_ROVER";
    MarcheAuto[MarcheAuto["VOLVO"] = 15] = "VOLVO";
    MarcheAuto[MarcheAuto["SAAB"] = 16] = "SAAB";
    MarcheAuto[MarcheAuto["PORSCHE"] = 17] = "PORSCHE";
    MarcheAuto[MarcheAuto["FERRARI"] = 18] = "FERRARI";
    MarcheAuto[MarcheAuto["LAMBORGHINI"] = 19] = "LAMBORGHINI";
    MarcheAuto[MarcheAuto["MASERATI"] = 20] = "MASERATI";
    MarcheAuto[MarcheAuto["BUGATTI"] = 21] = "BUGATTI";
    MarcheAuto[MarcheAuto["ASTON_MARTIN"] = 22] = "ASTON_MARTIN";
    MarcheAuto[MarcheAuto["BENTLEY"] = 23] = "BENTLEY";
    MarcheAuto[MarcheAuto["ROLLS_ROYCE"] = 24] = "ROLLS_ROYCE";
    MarcheAuto[MarcheAuto["JAGUAR"] = 25] = "JAGUAR";
    MarcheAuto[MarcheAuto["LOTUS"] = 26] = "LOTUS";
    MarcheAuto[MarcheAuto["TESLA"] = 27] = "TESLA";
    MarcheAuto[MarcheAuto["TATA"] = 28] = "TATA";
    MarcheAuto[MarcheAuto["MAHINDRA"] = 29] = "MAHINDRA";
    MarcheAuto[MarcheAuto["MARUTI"] = 30] = "MARUTI";
    MarcheAuto[MarcheAuto["HONDA"] = 31] = "HONDA";
    MarcheAuto[MarcheAuto["SUZUKI"] = 32] = "SUZUKI";
    MarcheAuto[MarcheAuto["NISSAN"] = 33] = "NISSAN";
    MarcheAuto[MarcheAuto["MITSUBISHI"] = 34] = "MITSUBISHI";
    MarcheAuto[MarcheAuto["MAZDA"] = 35] = "MAZDA";
    MarcheAuto[MarcheAuto["KIA"] = 36] = "KIA";
    MarcheAuto[MarcheAuto["HYUNDAI"] = 37] = "HYUNDAI";
    MarcheAuto[MarcheAuto["DAEWOO"] = 38] = "DAEWOO";
    MarcheAuto[MarcheAuto["CHEVROLET"] = 39] = "CHEVROLET";
    MarcheAuto[MarcheAuto["CADILLAC"] = 40] = "CADILLAC";
    MarcheAuto[MarcheAuto["BUICK"] = 41] = "BUICK";
    MarcheAuto[MarcheAuto["CHRYSLER"] = 42] = "CHRYSLER";
    MarcheAuto[MarcheAuto["DODGE"] = 43] = "DODGE";
    MarcheAuto[MarcheAuto["RAM"] = 44] = "RAM";
    MarcheAuto[MarcheAuto["GMC"] = 45] = "GMC";
    MarcheAuto[MarcheAuto["LINCOLN"] = 46] = "LINCOLN";
    MarcheAuto[MarcheAuto["MERCURY"] = 47] = "MERCURY";
    MarcheAuto[MarcheAuto["PONTIAC"] = 48] = "PONTIAC";
    MarcheAuto[MarcheAuto["SATURN"] = 49] = "SATURN";
    MarcheAuto[MarcheAuto["OLDSMOBILE"] = 50] = "OLDSMOBILE";
})(MarcheAuto || (MarcheAuto = {}));
let autoPier = MarcheAuto.ALFA_ROMEO;
console.log(MarcheAuto);
console.log(autoPier);
var MarcheMoto;
(function (MarcheMoto) {
    MarcheMoto[MarcheMoto["Aprilia"] = 10] = "Aprilia";
    MarcheMoto[MarcheMoto["Yamaha"] = 24] = "Yamaha";
    MarcheMoto[MarcheMoto["Suzuki"] = 67] = "Suzuki";
    MarcheMoto[MarcheMoto["Ducati"] = 25] = "Ducati";
    MarcheMoto[MarcheMoto["Benelli"] = 99] = "Benelli";
    MarcheMoto[MarcheMoto["Augusta"] = 25] = "Augusta";
    MarcheMoto[MarcheMoto["Harley_Davidson"] = 11] = "Harley_Davidson";
})(MarcheMoto || (MarcheMoto = {}));
console.log(MarcheMoto);
